### ISSUE TITLE
ERROR: UndefVarError: weight not defined

### ISSUE THREAD

**Issue by philtomson** [ayush1999/Keras.jl#1]
julia> using Kerasjulia> model, weight = Keras.load("/home/phil/Downloads/keras_structure.json", "/home/phil/Downloads/keras_weights.h5")
ERROR: UndefVarError: weight not defined
Stacktrace:
[1] (::Keras.##3#4)(::Keras.new_type) at /home/phil/.julia/v0.6/Keras/src/ops.jl:9
[2] get_ops(::Array{Any,1}) at /home/phil/.julia/v0.6/Keras/src/graph.jl:38
[3] load(::String, ::String) at /home/phil/.julia/v0.6/Keras/src/graph.jl:61
I looked at ops.jl:9:

```
ops = Dict{Symbol, Any}()

#weight = Keras.weights()

ops[:Input] = function(a)

    return vcall(:.+, a, 0)

end

ops[:Conv] = function(a)

    activation = a.fields["activation"]

    kernel_weight = permutedims(weight[a.fields["name"]][a.fields["name"]]["kernel:0"], (4,3,2,1))

    kernel_bias = weight[a.fields["name"]][a.fields["name"]]["bias:0"]

    strides = (a.fields["strides"]...)

    pads = (0,0)

    return vcall(:Conv, Symbol(activation), kernel_weight, kernel_bias, strides, pads)

end
```

Maybe weight shouldn't have been commented out there on line 2?

**Comment by ayush1999** [comment]
Sorry, I messed with the scope of variables in a commit. Fixed this now.
